[app]
name = "tlms"
port = 3500
host = "0.0.0.0"
environment = "TEST"

[network]
behind_proxy = false

[jwt]
access_expire = 7200
refresh_expire = 604800

[pg]
connect_timeout = 60
idle_timeout = 5
max = 1000